# Generated by Django 4.1.1 on 2022-10-27 16:23

import JadeActivity.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JadeActivity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitiesmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=JadeActivity.models.upload_image_path),
        ),
    ]
